name: ProxyDailyMonitor

on:
  workflow_dispatch:
  schedule:
    # github actions 使用的是国际标准时间，和北京时间有8个小时时差，时区换算：http://www.timebie.com/cn/universalbeijing.php
    - cron: "30 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: execute ProxyDailyMonitor
        run: mvn -B clean compile exec:java -Dexec.mainClass="com.leeyom.proxy.monitor.ProxyDailyMonitor" -Dexec.args="${{ secrets.BY_WAVE_USER_NAME }} ${{ secrets.BY_WAVE_PASSWORD }} ${{ secrets.MONO_CLOUD_USER_NAME }} ${{ secrets.MONO_CLOUD_PASSWORD }} ${{ secrets.TG_CHAT_ID }} ${{ secrets.TG_TOKEN }}" --file pom.xml